name: Wait for Container App
description: Wait for a specified condition on the latest container app revision
author: Damien Pontifex

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  subscrtion-id:
    description: 'Specifies the Azure subscription ID to use.'
    required: true
  resource-group-name:
    description:
      'Specifies the resource group name that the container app is in.'
    required: true
  container-app-name:
    description:
      'Specifies the name of the container app to wait for. If empty will wait
      for all container apps in the resource group.'
    required: false
  check-interval:
    description:
      'Specifies the interval in seconds to check the container app status.'
    required: false
    default: '2'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
